theme: jekyll-theme-tactile

title: Welcome to my homepage! 

description: this is a place where I keep my data analytics projects documented. They are currently mostly coding practices done at my leisure time to familiarize myself with different Python data analytics and visualization packages.
